sudo: required
services:
  - docker
before_install:
  - docker build -t hugovp/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run hugovp/react-test npm run test -- --coverage
after_success:
  - docker build -t hugovp/multi-client ./client 
  - docker build -t hugovp/multi-nginx ./nginx
  - docker build -t hugovp/multi-server ./server
  - docker build -t hugovp/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push hugovp/multi-client
  - docker push hugovp/multi-nginx
  - docker push hugovp/multi-server
  - docker push hugovp/multi-worker